§FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# monocle

API для получения радиолокационных данных. Все комментарии на русском, в соответствии со спецификацией. В именах сущностей часть названий, для которых удалось подобрать соотвествующий англоязычный аналог, передена на английский, часть оставлена в виде аббревиатур, соответсвующих русскоязычным аббревиатурам.

## Станции [/radar/list{?ids}{?title}{?limit}{?offset}]

### Получить список станций [GET]

+ Parameters
    * ids - Фильтр по id
    + title - Фильтр по названию
    + limit - Количество строк на странице
    + offset - Начиная с какой позиции выводить элементы

+ Response 200 (application/json)

        {
            "count": 5,
            "rows": [
                {
                    "id": 1,
                    "index": "0001",
                    "title": "Орловка",
                    "latitude": {
                        "type": "S",
                        "value": "43° 13' 46''"
                    },
                    "longitude": {
                        "type": "W",
                        "value": "12° 43' 17''"
                    },
                    "MASL": 0,
                    "HAAT_radar": 0,
                    "HAAT_AMS_DAD": 0,
                    "terrain_type": "land",
                    "current_program": {
                        "id": 1,
                        "title": "Обзор 50 км УМ 0-90°"
                    },
                    "schedule_status": "started",
                    "alarm_id": 0,
                    "record_local_reflection_map_duration": null,
                    "equipment_status": true,
                    "exchange_status": true,
                    "rotation_status": 60,
                    "max_dangerous_meteo": ""
                },
                {
                    "id": 2,
                    "index": "0002",
                    "title": "Чкаловский",
                    "latitude": {
                        "type": "S",
                        "value": "43° 13' 46''"
                    },
                    "longitude": {
                        "type": "W",
                        "value": "12° 43' 17''"
                    },
                    "MASL": 0,
                    "HAAT_radar": 0,
                    "HAAT_AMS_DAD": 0,
                    "terrain_type": "coldsea",
                    "current_program": {
                        "id": 1,
                        "title": "Обзор 50 км УМ 0-90°"
                    },
                    "schedule_status": "started",
                    "alarm_id": 0,
                    "record_local_reflection_map_duration": "PT0H12M0S",
                    "equipment_status": true,
                    "exchange_status": true,
                    "rotation_status": 60
                },
                {
                    "id": 3,
                    "index": "0003",
                    "title": "Елец",
                    "latitude": {
                        "type": "S",
                        "value": "43° 13' 46''"
                    },
                    "longitude": {
                        "type": "W",
                        "value": "12° 43' 17''"
                    },
                    "MASL": 0,
                    "HAAT_radar": 0,
                    "HAAT_AMS_DAD": 0,
                    "terrain_type": "warmsea",
                    "current_program": {
                        "id": 1,
                        "title": "Готовность"
                    },
                    "schedule_status": "stopped",
                    "alarm_id": 0,
                    "record_local_reflection_map_duration": null,
                    "equipment_status": true,
                    "exchange_status": true,
                    "rotation_status": 60
                },
                {
                    "id": 4,
                    "index": "0004",
                    "title": "Тула",
                    "latitude": {
                        "type": "S",
                        "value": "43° 15' 46''"
                    },
                    "longitude": {
                        "type": "W",
                        "value": "12° 41' 17''"
                    },
                    "MASL": 0,
                    "HAAT_radar": 1,
                    "HAAT_AMS_DAD": 0,
                    "terrain_type": "warmsea",
                    "current_program": {
                        "id": 1,
                        "title": "Готовность"
                    },
                    "schedule_status": "stopped",
                    "alarm_id": 0,
                    "record_local_reflection_map_duration": null,
                    "equipment_status": true,
                    "exchange_status": true,
                    "rotation_status": 60
                },
                {
                    "id": 5,
                    "index": "0005",
                    "title": "Щелково",
                    "latitude": {
                        "type": "S",
                        "value": "43° 15' 46''"
                    },
                    "longitude": {
                        "type": "W",
                        "value": "12° 41' 17''"
                    },
                    "MASL": 0,
                    "HAAT_radar": 1,
                    "HAAT_AMS_DAD": 0,
                    "terrain_type": "land",
                    "current_program": {
                        "id": 1,
                        "title": "Готовность"
                    },
                    "schedule_status": "stopped",
                    "alarm_id": 0,
                    "record_local_reflection_map_duration": null,
                    "equipment_status": true,
                    "exchange_status": true,
                    "rotation_status": 60
                }
            ]
        }

## Станция [/radar/{id}]

+ Parameters
    + id (number) - ID станции

### Получить станцию [GET]

+ Response 200 (application/json)

            {
                "id": 3,
                "index": "0003",
                "title": "Елец",
                "latitude": {
                    "type": "S",
                    "value": "43° 13' 46''"
                },
                "longitude": {
                    "type": "W",
                    "value": "12° 43' 17''"
                },
                "MASL": 0,
                "HAAT_radar": 0,
                "HAAT_AMS_DAD": 0,
                "terrain_type": "",
                "current_program": {
                    "id": 1,
                    "title": "Готовность"
                },
                "schedule_status": "started",
                "alarm_id": 0,
                "record_local_reflection_map_duration": null,
                "equipment_status": true,
                "exchange_status": true,
                "rotation_status": 60
            }
            
+ Response 404

### Обновить станцию [PUT]

+ Request (application/json)

        {
            "id": 3,
            "index": "0003",
            "title": "Елец",
            "latitude": {
                "type": "S",
                "value": "43° 13' 46''"
            },
            "longitude": {
                "type": "W",
                "value": "12° 43' 17''"
            },
            "MASL": 0,
            "HAAT_radar": 0,
            "HAAT_AMS_DAD": 0,
            "terrain_type": "land",
            "alarm_id": 0
        }

+ Response 422 (application/json)

    + Body

            {
                "index": "Невалидное значение",
                "index_not_unique": "Индекс не уникален",
                "title": "Невалидное значение",
                "terrainType": "Невалидное значение",
                "latitude": "Невалидное значение",
                "longitude": "Невалидное значение",
                "MASL": "Невалидное значение",
                "HAATRadar": "Невалидное значение",
                "HAATAMSDAD": "Невалидное значение",
                "alarmId": "Невалидное значение"
            }
            
+ Response 200 (application/json)
    
    + Body
        
            {
                "id": 3
                "index": "0003",
                "title": "Елец",
                "latitude": {
                    "type": "S",
                    "value": "43° 13' 46''"
                },
                "longitude": {
                    "type": "W",
                    "value": "12° 43' 17''"
                },
                "MASL": 0,
                "HAAT_radar": 0,
                "HAAT_AMS_DAD": 0,
                "terrain_type": "land",
                "alarm_id": 0,
                "record_local_reflection_map_duration": null,
                "equipment_status": true,
                "exchange_status": true,
                "rotation_status": 60
            }
        
+ Response 404

## Список каналов станции [/radar/{id}/settings/channel_list]

### Список каналов станции [GET]

+ Response 200 (application/json)

        {
            "count": 2,
            "rows": 
                [
                    {
                        "id": 1,
                        "frequency": 9111
                    },
                    {
                        "id": 2,
                        "frequency": 9335
                    }
                ]
        }
        
## Список РЛП станции [/radar/{id}/settings/rlp_list]

### Список РЛП станции [GET]

+ Response 200 (application/json)

        {
            "count": 4,
            "rows": 
                [
                    {
                        "id": 1,
                        "title": "Метеорологические явления",
                        "enable_altitude_scale": false,
                        "mixed_with_other_rlp": false
                    },
                    {
                        "id": 2,
                        "title": "Верхняя граница облачности",
                        "enable_altitude_scale": true,
                        "mixed_with_other_rlp": false
                    },
                    {
                        "id": 3,
                        "title": "Нижняя граница радиоэха",
                        "enable_altitude_scale": false,
                        "mixed_with_other_rlp": false
                    },
                    {
                        "id": 4,
                        "title": "Векторное поле скоростей",
                        "enable_altitude_scale": false,
                        "mixed_with_other_rlp": true
                    }
                ]
        }

## Список КС станции [/radar/{id}/settings/сs_list]

### Список КС станции [GET]

+ Response 200 (application/json)

        {
            "count": 2,
            "rows": 
                [
                    {
                        "id": 1,
                        "title": "Отражаемость",
                    },
                    {
                        "id": 2,
                        "title": "Интенсивность осадков",
                    }
                ]
        }


## Список минимальных опасных метеоявлений станции [/radar/{id}/settings/min_dangerous_meteo_list]

### Список минимальных опасных метеоявлений станции [GET]

+ Response 200 (application/json)

        {
            "count": 2,
            "rows": 
                [
                    {
                        "id": 1,
                        "title": "Облачность верхнего и среднего ярусов"
                    },
                    {
                        "id": 2,
                        "title": "Слоистая облачность"
                    }
                ]
        }
                
## Список метеоявлений станции [/radar/{id}/settings/meteo_list]

### Список метеоявлений станции [GET]

+ Response 200 (application/json)

        {
            "count": 5,
            "rows": 
                [
                    {
                        "id": 1,
                        "title": "Облачность (слоистообразная облачность)",
                        "items":
                        [
                            {
                                "id": 1,
                                "code": "Cl_dBZ23_min"
                                "title": "Минимальное значение радиолокационной отражаемости на уровнях Z 2 и Z 3",
                                "measurement unit": "dBZ",
                                "period": "all"
                            }
                        ],
                    },
                    {
                        "id": 2,
                        "title": "Град (слабый, умеренный, сильный)",
                        "items":
                        [
                            {
                                "id": 2,
                                "code": "Hl_Delta_H3_Ht0"
                                "title": "Пороговое значение разности высот H3 и H0",
                                "measurement unit": "м",
                                "period": "warm"
                            },
                            {
                                "id": 3,
                                "code": "Hl_dBZ_max"
                                "title": "Максимальное значение радиолокационной отражаемости по всему объему облака",
                                "measurement unit": "dBZ",
                                "period": "warm"
                            }
                        ],
                    }
                ]
        }
                
## Настройки станции [/radar/{id}/settings]

### Получить настройки станции [GET]

+ Response 200 (application/json)

            {
                "id": 3,
                "title": "Елец", 
                "antenna": {
                    "channel": {
                        "id": 2
                    },
                    "azimuth": 60,
                    "declination": 16
                },
                "calibration": {
                    "azimuth_north_fix": 0,
                    "cloud_velocity": "by_radial_velocity",
                    "manual_param": "isotherm_height",
                    "get_auto_param": true,
                    "temperature": 1.3,
                    "period": "warm",
                    "isotherm0_height": 200,
                    "isotherm22_height": 3,
                    "tropopause_height": 12000
                },
                "meteo_criterion": {
                    "min_dangerous_meteo": {
                        "id": 1
                    },
                    "isotherm_expire_period": 12,
                    "meteo_options": [
                        {
                            "id": 1,
                            "type": "Облачность (слоистообразная облачность)",
                            "warm": 10,
                            "cold": -10,
                            "code": "Cl_dBZ23_min",
                            "title": "Минимальное значение радиолокационной отражаемости на уровнях Z 2 и Z 3",
                            "measurement unit": "dBZ"
                        },
                        {
                            "id": 2,
                            "type": "Град (слабый, умеренный, сильный)",
                            "warm": 25,
                            "cold": -30,
                            "code": "Hl_dBZ_min",
                            "title": "Пороговое значение разности высот H3 и H0",
                            "measurement unit": "м"
                        },
                        {
                            "id": 3,
                            "type": "Град (слабый, умеренный, сильный)",
                            "warm": 45,
                            "cold": -20,
                            "code": "Hl_dBZ_max",
                            "title": "Максимальное значение радиолокационной отражаемости по всему объему облака",
                            "measurement unit": "м"
                        }
                    ]
                }
            }
            
### Редактирование настроек [PUT]

+ Request (application/json)

        {
                "id": 3,
                "antenna": {
                    "channel_id": 2,
                    "azimuth": 60,
                    "declination": 16
                },
                "calibration": {
                    "azimuth_north_fix": 0,
                    "cloud_velocity": "by_center_mass",
                    "manual_param": "ground_temperature",
                    "get_auto_param": true,
                    "temperature": 1.3,
                    "period": "warm",
                    "isotherm0_height": 200,
                    "isotherm22_height": 3,
                    "tropopause_height": 12000
                },
                "meteo_criterion": {
                    "min_dangerous_meteo_id": 1,
                    "isotherm_expire_period": 12,
                    "meteo_options": [
                        {
                            "id": 1,
                            "warm": 10,
                            "cold": -10
                        },
                        {
                            "id": 2,
                            "warm": 25,
                            "cold": -30
                        },
                        {
                            "id": 3,
                            "warm": 45,
                            "cold": -20
                        }
                    ]
                }
            }

+ Response 422

        {
            "antenna": {
                "channel": "Невалидное значение",
                "azimuth": "Невалидное значение",
                "declination": "Невалидное значение"
            },
            "calibration": {
                "azimuth_north_fix": "Невалидное значение",
                "cloud_velocity": "Невалидное значение",
                "manual_param": "Невалидное значение",
                "get_auto_param": "Невалидное значение",
                "temperature": "Невалидное значение",
                "period": "Невалидное значение",
                "isotherm0_height": "Невалидное значение",
                "isotherm22_height": "Невалидное значение",
                "tropopause_height": "Невалидное значение"
            },
            "meteo_criterion": {
                "min_dangerous_meteo": "Невалидное значение",
                "isotherm_expire_period": "Невалидное значение",
                "meteo_options": {
                    "common": "Невалидное значение",
                    "rows": [
                        {
                            "id": 1,
                            "warm": "Невалидное значение"
                        },
                        {
                            "id": 2,
                            "warm": "Невалидное значение",
                            "cold": "Невалидное значение"
                        }
                    ]
                }
            }
        }

+ Response 200 (application/json)

            {
                "id": 3,
                "title": "Елец",
                "antenna": {
                    "channel": {
                        "id": 2
                    },
                    "azimuth": 60,
                    "declination": 16
                },
                "calibration": {
                    "azimuth_north_fix": 0,
                    "cloud_velocity": "by_center_mass",
                    "manual_param": "isotherm_height",
                    "get_auto_param": true,
                    "temperature": 1.3,
                    "period": "warm",
                    "isotherm0_height": 200,
                    "isotherm22_height": 3,
                    "tropopause_height": 12000
                },
                "meteo_criterion": {
                    "min_dangerous_meteo": {
                        "id": 1
                    },
                    "isotherm_expire_period": 12,
                    "meteo_options": [
                        {
                            "id": 1,
                            "type": "Облачность (слоистообразная облачность)",
                            "warm": 10,
                            "cold": -10,
                            "code": "Cl_dBZ23_min",
                            "title": "Минимальное значение радиолокационной отражаемости на уровнях Z 2 и Z 3",
                            "measurement unit": "dBZ"
                        },
                        {
                            "id": 2,
                            "type": "Град (слабый, умеренный, сильный)",
                            "warm": 25,
                            "cold": -30,
                            "code": "Hl_dBZ_min",
                            "title": "Пороговое значение разности высот H3 и H0",
                            "measurement unit": "м"
                        },
                        {
                            "id": 3,
                            "type": "Град (слабый, умеренный, сильный)",
                            "warm": 45,
                            "cold": -20,
                            "code": "Hl_dBZ_max",
                            "title": "Максимальное значение радиолокационной отражаемости по всему объему облака",
                            "measurement unit": "м"
                        }
                    ]
                }
            }
            
+ Response 409

+ Response 404

## Расписание станции [/radar/{id}/schedule]

### Получить расписание станции [GET]

+ Response 200 (application/json)

            {
                "count": 2,
                "rows": 
                    [
                        {
                            "id": 1,
                            "program": {
                                "id": 2,
                                "title": "Обзор 50 км УМ 0-90°",
                                "duration": "PT0H10M0S"
                            },
                            "start": "PT0H0M0S"
                        },
                        {
                            "id": 2,
                            "program": {
                                "id": 3,
                                "title": "Сектор 50 км 60-30°",
                                "duration": "PT0H12M0S"
                            },
                            "start": "PT0H12M0S"
                        }
                    ]
            }
+ Response 409
            
### Обновить расписание станции [PUT]

+ Request (application/json)

        [
            {
                "id": 1,
                "program_id": 2,
                "start": "PT0H0M0S"
            },
            {
                "id": 2,
                "program_id": 3,
                "start": "PT0H12M0S"
            }
        ]

+ Response 200 (application/json)

            {
                "count": 5,
                "rows":
                    [
                        {
                            "id": 1,
                            "program": {
                                "id": 2,
                                "title": "Обзор 50 км УМ 0-90°",
                                "duration": "PT0H10M0S"
                            },
                            "start": "PT0H0M0S"
                        },
                        {
                            "id": 2,
                            "program": {
                                "id": 3,
                                "title": "Сектор 50 км 60-30°",
                                "duration": "PT0H12M0S"
                            },
                            "start": "PT0H12M0S"
                        }
                    ]
            }

+ Response 422

        [
            {
                "index": 0,
                "start": "Программа полностью не выполняется. Измените время начала или поменяйте программу."
            },
            {
                "index": 2,
                "start": "Программа полностью не выполняется. Измените время начала или поменяйте программу."
            }
        ]

+ Response 409

+ Response 404

## Карта местных отражений [/radar/{id}/local_reflection_map]

### Карта местных отражений [POST]

+ Response 200 (application/json)

            {
                "record_local_reflection_map_duration": "PT0H12M0S"
            }

+ Response 409

+ Response 404

## НАМС и метеостатистика [/radar/{id}/meteoinfo]

### НАМС и метеостатистика [GET]

+ Response 200 (application/json)

        {
            "temperature": -3,
            "humidity": 72,
            "pressure": 780,
            "cloud_transfer_azimuth": 319,
            "cloud_transfer_speed": 3,
            "cloud_base": 1000,
            "cloud_top": 4000
            "wind_azimuth": 319,
            "wind_speed": 3,
            "max_atmospheric_process": "Ливень умеренный",
            
            
        }
            
## РЛП [/radar/{id}/RLP{?rlp_ids}{?view_type}{?only_dangerous}{?altitude}{?from}{?to}]

### Получить РЛП [GET]

+ Parameters
    + id (number) - ID станции
    * rlp_ids - Фильтр по id
    * view_type - Карта метеоявлений в ячейках или в контурах
    * only_dangerous - отображать только ОМЯ
    * altitude - Высота в метрах
    * from - Начальный период поиска
    * to - Конечный период поиска
    

+ Response 200 (application/json)

        {
            "type": "FeatureCollection",
            "features": [
                {
                "type": "Feature",
                "properties": {
                "stroke": "#555555",
                "stroke-width": 2,
                "stroke-opacity": 1,
                "fill": "#3748b0",
                "fill-opacity": 0.5
                },
                "geometry": {dd 
                "type": "Polygon",
                "coordinates": [
                [
                [
                36.995086669921875,
                55.926124639200474
                ],
                [
                36.925048828125,
                55.82134464477078
                ],
                [
                37.143402099609375,
                55.72401656896143
                ],
                [
                37.146148681640625,
                55.8159439039053
                ],
                [
                37.24639892578125,
                55.876081238490315
                ],
                [
                36.995086669921875,
                55.926124639200474
                ]
                ]
                ]
                }
                },
                {
                "type": "Feature",
                "properties": {
                "stroke": "#555555",
                "stroke-width": 2,
                "stroke-opacity": 1,
                "fill": "#c43030",
                "fill-opacity": 0.5
                },
                "geometry": {
                "type": "Polygon",
                "coordinates": [
                [
                [
                37.937164306640625,
                55.95381321086168
                ],
                [
                37.82318115234375,
                55.86144097132764
                ],
                [
                37.9962158203125,
                55.73020335605107
                ],
                [
                38.21868896484375,
                55.76034990679016
                ],
                [
                38.189849853515625,
                55.898416270776835
                ],
                [
                37.937164306640625,
                55.95381321086168
                ]
                ],
                [
                [
                37.9742431640625,
                55.868376522659915
                ],
                [
                38.10333251953125,
                55.84371115792938
                ],
                [
                38.011322021484375,
                55.811314100800935
                ],
                [
                37.9742431640625,
                55.868376522659915
                ]
                ]
                ]
                }
                },
                {
                "type": "Feature",
                "properties": {
                "stroke": "#555555",
                "stroke-width": 2,
                "stroke-opacity": 1,
                "fill": "#1ae330",
                "fill-opacity": 0.5
                },
                "geometry": {
                "type": "Polygon",
                "coordinates": [
                [
                [
                37.451019287109375,
                55.66751683835719
                ],
                [
                37.17086791992187,
                55.56281575575881
                ],
                [
                37.496337890625,
                55.36038057233305
                ],
                [
                37.766876220703125,
                55.49130362820423
                ],
                [
                37.451019287109375,
                55.66751683835719
                ]
                ],
                [
                [
                37.368621826171875,
                55.56747507540018
                ],
                [
                37.558135986328125,
                55.54883448072051
                ],
                [
                37.541656494140625,
                55.488969521953074
                ],
                [
                37.39471435546875,
                55.49285962220559
                ],
                [
                37.368621826171875,
                55.56747507540018
                ]
                ]
                ]
                }
                },
                {
                "type": "Feature",
                "properties": {
                "stroke": "#555555",
                "stroke-width": 2,
                "stroke-opacity": 1,
                "fill": "#e7f30a",
                "fill-opacity": 0.5
                },
                "geometry": {
                "type": "Polygon",
                "coordinates": [
                [
                [
                37.368621826171875,
                55.56747507540018
                ],
                [
                37.558135986328125,
                55.54883448072051
                ],
                [
                37.541656494140625,
                55.488969521953074
                ],
                [
                37.39471435546875,
                55.49285962220559
                ],
                [
                37.368621826171875,
                55.56747507540018
                ]
                ]
                ]
                }
                }
            ]
        }
        
## КС [/radar/{id}/CS{?cs_ids}{?type}{?altitude}{?from}{?to}]

### Получить КС [GET]

+ Parameters
    + id (number) - ID станции
    * cs_ids - Фильтр по id
    * type -  CAPPI или PPI
    * altitude - Высота в метрах
    * from - Начальный период поиска
    * to - Конечный период поиска
    

+ Response 200 (application/json)

        {
            "type": "FeatureCollection",
            "features": [
                {
                "type": "Feature",
                "properties": {
                "stroke": "#555555",
                "stroke-width": 2,
                "stroke-opacity": 1,
                "fill": "#3748b0",
                "fill-opacity": 0.5
                },
                "geometry": {dd 
                "type": "Polygon",
                "coordinates": [
                [
                [
                36.995086669921875,
                55.926124639200474
                ],
                [
                36.925048828125,
                55.82134464477078
                ],
                [
                37.143402099609375,
                55.72401656896143
                ],
                [
                37.146148681640625,
                55.8159439039053
                ],
                [
                37.24639892578125,
                55.876081238490315
                ],
                [
                36.995086669921875,
                55.926124639200474
                ]
                ]
                ]
                }
                },
                {
                "type": "Feature",
                "properties": {
                "stroke": "#555555",
                "stroke-width": 2,
                "stroke-opacity": 1,
                "fill": "#c43030",
                "fill-opacity": 0.5
                },
                "geometry": {
                "type": "Polygon",
                "coordinates": [
                [
                [
                37.937164306640625,
                55.95381321086168
                ],
                [
                37.82318115234375,
                55.86144097132764
                ],
                [
                37.9962158203125,
                55.73020335605107
                ],
                [
                38.21868896484375,
                55.76034990679016
                ],
                [
                38.189849853515625,
                55.898416270776835
                ],
                [
                37.937164306640625,
                55.95381321086168
                ]
                ],
                [
                [
                37.9742431640625,
                55.868376522659915
                ],
                [
                38.10333251953125,
                55.84371115792938
                ],
                [
                38.011322021484375,
                55.811314100800935
                ],
                [
                37.9742431640625,
                55.868376522659915
                ]
                ]
                ]
                }
                },
                {
                "type": "Feature",
                "properties": {
                "stroke": "#555555",
                "stroke-width": 2,
                "stroke-opacity": 1,
                "fill": "#1ae330",
                "fill-opacity": 0.5
                },
                "geometry": {
                "type": "Polygon",
                "coordinates": [
                [
                [
                37.451019287109375,
                55.66751683835719
                ],
                [
                37.17086791992187,
                55.56281575575881
                ],
                [
                37.496337890625,
                55.36038057233305
                ],
                [
                37.766876220703125,
                55.49130362820423
                ],
                [
                37.451019287109375,
                55.66751683835719
                ]
                ],
                [
                [
                37.368621826171875,
                55.56747507540018
                ],
                [
                37.558135986328125,
                55.54883448072051
                ],
                [
                37.541656494140625,
                55.488969521953074
                ],
                [
                37.39471435546875,
                55.49285962220559
                ],
                [
                37.368621826171875,
                55.56747507540018
                ]
                ]
                ]
                }
                },
                {
                "type": "Feature",
                "properties": {
                "stroke": "#555555",
                "stroke-width": 2,
                "stroke-opacity": 1,
                "fill": "#e7f30a",
                "fill-opacity": 0.5
                },
                "geometry": {
                "type": "Polygon",
                "coordinates": [
                [
                [
                37.368621826171875,
                55.56747507540018
                ],
                [
                37.558135986328125,
                55.54883448072051
                ],
                [
                37.541656494140625,
                55.488969521953074
                ],
                [
                37.39471435546875,
                55.49285962220559
                ],
                [
                37.368621826171875,
                55.56747507540018
                ]
                ]
                ]
                }
                }
            ]
        }

+ Response 404

## Метеоинформация в указанной точке [/radar/{id}/{product_type}/point/{?product_ids}{?coordinates}]

### Получить метеоинформацию в указанной точке [GET]

+ Parameters
    + id (number) - ID станции
    + product_type - РЛП или КС
    * product_ids -  Фильтр по id
    * coordinates - Координаты точки
    

+ Response 200 (application/json)

        {
            "atmospheric_process": "Ливень слабый",
            ...
        }
            
## Программы [/program/list{?mode}{?title}{?limit}{?offset}]

### Список программ [GET]

+ Parameters
    + mode - Фильтр режима
    + title - Фильтр по названию
    + limit - Количество строк на странице
    + offset - Начиная с какой позиции выводить элементы

+ Response 200 (application/json)

        {
            "count": 4,
            "rows": [
                {
                    "id": 1,
                    "title": "Обзор 50 км УМ 0-90°",
                    "duration": "PT1H10M10S",
                    "mode": "circular",
                    "distance": 25,
                    "elevation_change_azimuth": 0,
                    "left_border_azimuth": 0,
                    "right_border_azimuth": 0,
                    "elevation_program": [{
                      "value": 1
                    }],
                    "blocking_program": [
                      {
                        "start": 0,
                        "end": 0
                      }
                    ]
                },
                {
                    "id": 2,
                    "title": "Сектор 50 км 60-30°",
                    "duration": "PT0H12M0S",
                    "mode": "sector",
                    "distance": 50,
                    "elevation_change_azimuth": 0,
                    "left_border_azimuth": 0,
                    "right_border_azimuth": 0,
                    "elevation_program": [{
                      "value": 1
                    }],
                    "blocking_program": [
                      {
                        "start": 0,
                        "end": 0
                      }
                    ]
                },
                {
                    "id": 3,
                    "title": "Обзор 100 км УМ 0-90°",
                    "duration": "PT0H15M0S",
                    "mode": "circular",
                    "distance": 100,
                    "elevation_change_azimuth": 0,
                    "left_border_azimuth": 0,
                    "right_border_azimuth": 0,
                    "elevation_program": [{
                      "value": 1
                    }],
                    "blocking_program": [
                      {
                        "start": 0,
                        "end": 0
                      }
                    ]
                },
                {
                    "id": 4,
                    "title": "Сектор 75 км 60-30°",
                    "duration": "PT0H18M0S",
                    "mode": "sector",
                    "distance": 150,
                    "elevation_change_azimuth": 0,
                    "left_border_azimuth": 0,
                    "right_border_azimuth": 0,
                    "elevation_program": [{
                      "value": 1
                    }],
                    "blocking_program": [
                      {
                        "start": 0,
                        "end": 0
                      }
                    ]
                }
            ]
        }
        
## Программа [/program/{id}]

+ Parameters
    + id (number) - ID программы

### Получить программу [GET]

+ Response 200 (application/json)

            {
                "id": 1,
                "title": "Обзор 50 км УМ 0-90°",
                "duration": "PT0H10M0S",
                "mode": "circular",
                "distance": 25,
                "elevation_change_azimuth": 0,
                "left_border_azimuth": 0,
                "right_border_azimuth": 0,
                "elevation_program": [{
                  "value": 1
                }],
                "blocking_program": [
                  {
                    "start": 0,
                    "end": 0
                  }
                ]
            }
            
+ Response 404

### Создать программу [POST /program]

+ Request (application/json)

        {
            "title": "Сектор 75 км 60-30°",
            "duration": "PT0H18M0S",
            "mode": "sector",
            "distance": 150,
            "elevation_change_azimuth": 0,
            "left_border_azimuth": 0,
            "right_border_azimuth": 0,
            "elevation_program": [{
              "value": 1
            }],
            "blocking_program": [
              {
                "start": 0,
                "end": 0
              }
            ]
        }

+ Response 422 (application/json)

    + Body

            {
                "title": "Невалидное значение",
                "duration": "Невалидное значение",
                "mode": "Невалидное значение",
                "distance": "Невалидное значение",
                "elevation_change_azimuth": "Невалидное значение",
                "left_border_azimuth": "Невалидное значение",
                "right_border_azimuth": "Невалидное значение",
                "elevation_program": {
                    "common": "Невалидное значение",
                    "rows": [{
                        "index": 0,
                        "value": "Невалидное значение"
                    }]
                },
                "blocking_program": {
                    "common": "",
                    "rows": [{
                        "index": 0,
                        "start": "Невалидное значение",
                        "end": "Невалидное значение"
                    }]
                }
            }
            
+ Response 201 (application/json)

    + Body
    
            {
                "id": 4,
                "title": "Сектор 75 км 60-30°",
                "duration": "PT0H18M0S",
                "mode": "sector",
                "distance": 150,
                "elevation_change_azimuth": 0,
                "left_border_azimuth": 0,
                "right_border_azimuth": 0,
                "elevation_program": [{
                  "value": 1
                }],
                "blocking_program": [
                  {
                    "start": 0,
                    "end": 0
                  }
                ]
            }
            
## Удалить программу [DELETE]

+ Response 204

+ Response 409
        
        {
            "count": 2,
            "radar_ids": [1,4]
        }
    
+ Response 404

### Обновить программу [/program{?ignore_conflict}]

+ Parameters
    * ignore_conflict - указываем этот параметр при редактировании, когда хотим сохранить измененеия несмотря на то, что программа используется в расписании.
    
### Обновить программу [PUT]

+ Request (application/json)

        {
            "id": 1,
            "title": "Обзор 50 км УМ 0-90°",
            "duration": "PT0H10M0S",
            "mode": "circular",
            "distance": 25,
            "elevation_change_azimuth": 0,
            "left_border_azimuth": 0,
            "right_border_azimuth": 0,
            "elevation_program": [{
              "value": 1
            }],
            "blocking_program": [
              {
                "start": 0,
                "end": 0
              }
            ]
        }

+ Response 200 (application/json)

    + Body

            {
                "id": 1,
                "title": "Обзор 50 км УМ 0-90°",
                "duration": "PT0H10M0S",
                "mode": "circular",
                "distance": 25,
                "elevation_change_azimuth": 0,
                "left_border_azimuth": 0,
                "right_border_azimuth": 0,
                "elevation_program": [{
                  "value": 1
                }],
                "blocking_program": [
                  {
                    "start": 0,
                    "end": 0
                  }
                ]
            }
            
+ Response 422 (application/json)

    + Body

            {
                "title": "Невалидное значение",
                "duration": "Невалидное значение",
                "mode": "Невалидное значение",
                "distance": "Невалидное значение",
                "elevation_change_azimuth": "Невалидное значение",
                "left_border_azimuth": "Невалидное значение",
                "right_border_azimuth": "Невалидное значение",
                "elevation_program": {
                    "common": "Невалидное значение",
                    "rows": [{
                        "index": 0,
                        "value": "Невалидное значение"
                    }]
                },
                "blocking_program": {
                    "common": "",
                    "rows": [{
                        "index": 0,
                        "start": "Невалидное значение",
                        "end": "Невалидное значение"
                    }]
                }
            }

+ Response 409
        
        {
            "count": 2,
            "radar_ids": [1,4]
        }
        
+ Response 404    

## Журнал событий [/radar_log/list{?type}{?radar}{?from}{?to}{?message}{?limit}{?offset}]

### Получить список событий [GET]

+ Parameters
    * type - Тип события, информация или ошибка (error|info)
    + radar - Id станции
    + from - Начальный период поиска
    + to - Конечный период поиска
    + message - Сообщение
    + limit - Количество строк на странице
    + offset - Начиная с какой позиции выводить элементы

+ Response 200 (application/json)

        {
            "count": 4,
            "rows": 
                [
                    {
                        "id": 1,
                        "date": "2017-05-15T08:30:00",
                        "type": "info",
                        "radar": {
                            "id": 6,
                            "title": "Щелково"
                        },
                        "message": "Превышен период обновления параметров калибровки."
                    },
                    {
                        "id": 2,
                        "date": "2017-05-15T08:30:00",
                        "type": "error",
                        "radar": {
                            "id": 1,
                            "title": "Орловка"
                        },
                        "message": "Ошибка подключения к МРЛС. Проверьте настройки."
                    },
                    {
                        "id": 3,
                        "date": "2017-05-15T08:30:00",
                        "type": "info",
                        "radar": {
                            "id": 6,
                            "title": "Щелково"
                        },
                        "message": "Карта местных отражений очищена"
                    },
                    {
                        "id": 4,
                        "date": "2017-05-15T08:30:00",
                        "type": "info",
                        "radar": {
                            "id": 2,
                            "title": "Чкаловский"
                        },
                        "message": "Карта местных отражений очищена"
                    }
                ]
        }

## Настройки экспорта BUFR [/settings/bufr]
 
### Получить список настроек экспорта bufr [GET]

+ Response 200 (application/json)
        
        {
            "count": 2,
            "rows": 
                [
                    {
                        "active": true,
                        "ip": "40.72.241.112",
                        "port": 21,
                        "path": "/var/lib/monocle/data/",
                        "radars": [
                            {
                                "id": 1,
                                "title": "Орловка"
                            },
                            {
                                "id": 2,
                                "title": "Чкаловский"
                            },
                            {
                                "id": 3,
                                "title": "Братск"
                            }
                        ]
                    },
                    {
                        "active": false,
                        "ip": "40.72.241.112",
                        "port": 21,
                        "path": "/var/lib/monocle/data/",
                        "radars": [
                            {
                                "id": 3,
                                "title": "Братск"
                            }
                        ]
                    }
                ]
        }
 
## Обновить список настроек экспорта BUFR [PUT]

+ Request (application/json)
    
        [
            {
                "active": true,
                "ip": "40.72.241.112",
                "port": 21,
                "path": "/var/lib/monocle/data/",
                "radars": [
                    {
                        "id": 1,
                        "title": "Орловка"
                    },
                    {
                        "id": 2,
                        "title": "Чкаловский"
                    },
                    {
                        "id": 3,
                        "title": "Братск"
                    }
                ]
            },
            {
                "active": false,
                "ip": "40.72.241.112",
                "port": 21,
                "path": "/var/lib/monocle/data/",
                "radars": [
                    {
                        "id": 3,
                        "title": "Братск"
                    }
                ]
            }
        ]
        
+ Response 200 (application/json)
        
        {
            "count": 2,
            "rows": 
                [
                    {
                        "active": true,
                        "ip": "40.72.241.112",
                        "port": 21,
                        "path": "/var/lib/monocle/data/",
                        "radars": [
                            {
                                "id": 1,
                                "title": "Орловка"
                            },
                            {
                                "id": 2,
                                "title": "Чкаловский"
                            },
                            {
                                "id": 3,
                                "title": "Братск"
                            }
                        ]
                    },
                    {
                        "active": false,
                        "ip": "40.72.241.112",
                        "port": 21,
                        "path": "/var/lib/monocle/data/",
                        "radars": [
                            {
                                "id": 3,
                                "title": "Братск"
                            }
                        ]
                    }
                ]
        }

    
+ Response 422 (application/json)

    + Body
            
            {
                "count": 1,
                "rows": 
                    [
                        {
                            "index": 1,
                            "active": "Невалидное значение",
                            "ip": "Невалидное значение",
                            "port": "Невалидное значение",
                            "path": "Невалидное значение",
                            "radars": "Невалидное значение"
                        }
                    ]
            }
            
## Построение карт [/settings/maps]
 
### Получить настройки для построения карт [GET]

+ Response 200 (application/json)
        
        {
            "count": 7,
            "rows":
                [
                    {
                        "id": 1,
                        "title": "Векторное поле скоростей",
                        "params": [
                            {
                                "id": 1,
                                "title": "Шаг по горизонтали",
                                "meashure_unit": "м",
                                "type": "Режим Обзор",
                                "value": 100
                            },
                            {
                                "id": 2,
                                "title": "Шаг по вертикали",
                                "meashure_unit": "м",
                                "type": "Режим Обзор",
                                "value": 100
                            },
                            {
                                "id": 3,
                                "title": "Шаг по горизонтали",
                                "meashure_unit": "м",
                                "type": "Режим Сектор (ширина < 70 градусов)",
                                "value": 200
                            },
                            {
                                "id": 4,
                                "title": "Шаг по вертикали",
                                "meashure_unit": "м",
                                "type": "Режим Сектор (ширина < 70 градусов)",
                                "value": 200
                            }
                        ]
                    },
                    {
                        "id": 2,
                        "title": "Поля сдвигов ветра",
                        "params": [
                            {
                                "id": 1,
                                "title": "Максимальная высота",
                                "meashure_unit": "м",
                                "type": "Режим Обзор",
                                "value": 100
                            },
                            {
                                "id": 2,
                                "title": "Максимальная дальность",
                                "meashure_unit": "м",
                                "type": "Режим Обзор",
                                "value": 100
                            },
                            {
                                "id": 3,
                                "title": "Максимальная высота",
                                "meashure_unit": "м",
                                "type": "Режим Сектор (ширина < 70 градусов)",
                                "value": 200
                            },
                            {
                                "id": 4,
                                "title": "Максимальная дальность",
                                "meashure_unit": "м",
                                "type": "Режим Сектор (ширина < 70 градусов)",
                                "value": 200
                            },
                            {
                                "id": 5,
                                "title": "Шаг по горизонтали",
                                "meashure_unit": "м",
                                "value": 200
                            },
                            {
                                "id": 6,
                                "title": "Шаг по вертикали",
                                "meashure_unit": "м",
                                "value": 200
                            }
                        ]
                    },
                    {
                        "id": 3,
                        "title": "Метеоявления",
                        "params": [
                            {
                                "id": 1,
                                "title": "Размер ячейки карты метеоявлений",
                                "meashure_unit": "м",
                                "value": 100
                            },
                            {
                                "id": 2,
                                "title": "Степень генерализации контуров",
                                "meashure_unit": "ед",
                                "value": 3
                            },
                            {
                                "id": 3,
                                "title": "Величина расширения контуров",
                                "meashure_unit": "ячеек",
                                "value": 3
                            }
                        ]
                    },
                    {
                        "id": 4,
                        "title": "Вектор",
                        "params": [
                            {
                                "id": 1,
                                "title": "Размер вектора",
                                "meashure_unit": "ед",
                                "value": 5
                            },
                            {
                                "id": 2,
                                "title": "Толщина вектора",
                                "meashure_unit": "ед",
                                "value": 3
                            }
                        ]
                    },
                    {
                        "id": 5,
                        "title": "Вертикальное сечение",
                        "params": [
                            {
                                "id": 1,
                                "title": "Шаг по горизонтали",
                                "meashure_unit": "м",
                                "value": 100
                            },
                            {
                                "id": 2,
                                "title": "Шаг по вертикали",
                                "meashure_unit": "м",
                                "value": 100
                            }
                        ]
                    },
                    {
                        "id": 6,
                        "title": "Накопленные осадки",
                        "params": [
                            {
                                "id": 1,
                                "title": "Размер ячейки карты накопленных осадков",
                                "meashure_unit": "м",
                                "value": 100
                            }
                        ]
                    },
                    {
                        "id": 7,
                        "title": "Вертикально интегрированная водность",
                        "params": [
                            {
                                "id": 1,
                                "title": "Размер ячейки карты вертикально интегрированной водности",
                                "meashure_unit": "м",
                                "value": 100
                            }
                        ]
                    }
                ]
        }
                    
 
### Обновить настройки для построения карт [PUT]

+ Request (application/json)
    
        [
            {
                "id": 1,
                "params": [
                    {
                        "id": 1,
                        "value": 100
                    },
                    {
                        "id": 2,
                        "value": 100
                    },
                    {
                        "id": 3,
                        "value": 200
                    },
                    {
                        "id": 4,
                        "value": 200
                    }
                ]
            },
            {
                "id": 2,
                "params": [
                    {
                        "id": 1,
                        "value": 100
                    },
                    {
                        "id": 2,
                        "value": 100
                    },
                    {
                        "id": 3,
                        "value": 200
                    },
                    {
                        "id": 4,
                        "value": 200
                    },
                    {
                        "id": 5,
                        "value": 200
                    },
                    {
                        "id": 6,
                        "value": 200
                    }
                ]
            },
            {
                "id": 3,
                "params": [
                    {
                        "id": 1,
                        "value": 100
                    },
                    {
                        "id": 2,
                        "value": 3
                    },
                    {
                        "id": 3,
                        "value": 3
                    }
                ]
            },
            {
                "id": 4,
                "params": [
                    {
                        "id": 1,
                        "value": 5
                    },
                    {
                        "id": 2,
                        "value": 3
                    }
                ]
            },
            {
                "id": 5,
                "params": [
                    {
                        "id": 1,
                        "value": 100
                    },
                    {
                        "id": 2,
                        "value": 100
                    }
                ]
            },
            {
                "id": 6,
                "params": [
                    {
                        "id": 1,
                        "value": 100
                    }
                ]
            },
            {
                "id": 7,
                "params": [
                    {
                        "id": 1,
                        "value": 100
                    }
                ]
            }
        ]
        
+ Response 200 (application/json)
        
        {
            "count": 7,
            "rows":
                [
                    {
                        "id": 1,
                        "title": "Векторное поле скоростей",
                        "params": [
                            {
                                "id": 1,
                                "title": "Шаг по горизонтали",
                                "meashure_unit": "м",
                                "type": "Режим Обзор",
                                "value": 100
                            },
                            {
                                "id": 2,
                                "title": "Шаг по вертикали",
                                "meashure_unit": "м",
                                "type": "Режим Обзор",
                                "value": 100
                            },
                            {
                                "id": 3,
                                "title": "Шаг по горизонтали",
                                "meashure_unit": "м",
                                "type": "Режим Сектор (ширина < 70 градусов)",
                                "value": 200
                            },
                            {
                                "id": 4,
                                "title": "Шаг по вертикали",
                                "meashure_unit": "м",
                                "type": "Режим Сектор (ширина < 70 градусов)",
                                "value": 200
                            }
                        ]
                    },
                    {
                        "id": 2,
                        "title": "Поля сдвигов ветра",
                        "params": [
                            {
                                "id": 1,
                                "title": "Максимальная высота",
                                "meashure_unit": "м",
                                "type": "Режим Обзор",
                                "value": 100
                            },
                            {
                                "id": 2,
                                "title": "Максимальная дальность",
                                "meashure_unit": "м",
                                "type": "Режим Обзор",
                                "value": 100
                            },
                            {
                                "id": 3,
                                "title": "Максимальная высота",
                                "meashure_unit": "м",
                                "type": "Режим Сектор (ширина < 70 градусов)",
                                "value": 200
                            },
                            {
                                "id": 4,
                                "title": "Максимальная дальность",
                                "meashure_unit": "м",
                                "type": "Режим Сектор (ширина < 70 градусов)",
                                "value": 200
                            },
                            {
                                "id": 5,
                                "title": "Шаг по горизонтали",
                                "meashure_unit": "м",
                                "value": 200
                            },
                            {
                                "id": 6,
                                "title": "Шаг по вертикали",
                                "meashure_unit": "м",
                                "value": 200
                            }
                        ]
                    },
                    {
                        "id": 3,
                        "title": "Метеоявления",
                        "params": [
                            {
                                "id": 1,
                                "title": "Размер ячейки карты метеоявлений",
                                "meashure_unit": "м",
                                "value": 100
                            },
                            {
                                "id": 2,
                                "title": "Степень генерализации контуров",
                                "meashure_unit": "ед",
                                "value": 3
                            },
                            {
                                "id": 3,
                                "title": "Величина расширения контуров",
                                "meashure_unit": "ячеек",
                                "value": 3
                            }
                        ]
                    },
                    {
                        "id": 4,
                        "title": "Вектор",
                        "params": [
                            {
                                "id": 1,
                                "title": "Размер вектора",
                                "meashure_unit": "ед",
                                "value": 5
                            },
                            {
                                "id": 2,
                                "title": "Толщина вектора",
                                "meashure_unit": "ед",
                                "value": 3
                            }
                        ]
                    },
                    {
                        "id": 5,
                        "title": "Вертикальное сечение",
                        "params": [
                            {
                                "id": 1,
                                "title": "Шаг по горизонтали",
                                "meashure_unit": "м",
                                "value": 100
                            },
                            {
                                "id": 2,
                                "title": "Шаг по вертикали",
                                "meashure_unit": "м",
                                "value": 100
                            }
                        ]
                    },
                    {
                        "id": 6,
                        "title": "Накопленные осадки",
                        "params": [
                            {
                                "id": 1,
                                "title": "Размер ячейки карты накопленных осадков",
                                "meashure_unit": "м",
                                "value": 100
                            }
                        ]
                    },
                    {
                        "id": 7,
                        "title": "Вертикально интегрированная водность",
                        "params": [
                            {
                                "id": 1,
                                "title": "Размер ячейки карты вертикально интегрированной водности",
                                "meashure_unit": "м",
                                "value": 100
                            }
                        ]
                    }
                ]
        }

    
+ Response 422 (application/json)

    + Body
    
            {
                "count": 5,
                "rows": 
                    [
                        {
                            "id": 1,
                            "params": [
                                {
                                    "id": 1,
                                    "value": "Невалидное значение"
                                },
                                {
                                    "id": 2,
                                    "value": "Невалидное значение"
                                },
                                {
                                    "id": 3,
                                    "value": "Невалидное значение"
                                }
                            ]
                        },
                        {
                            "id": 6,
                            "params": [
                                {
                                    "id": 1,
                                    "value": "Невалидное значение"
                                }
                            ]
                        }
                    ]
            }

## Список настроек цветовой шкалы [/settings/color_scale/list]

### Получить список настроек цветовой шкалы [GET]

+ Response 200 (application/json)
        
        {
            "count": 2,
            "rows":
                [
                    {
                        "id": 1,
                        "title": "Отражаемость",
                        "params":
                            [
                                {
                                    "id": 1,
                                    "value": 30,
                                    "color": "#010178"
                                },
                                {
                                    "id": 2,
                                    "value": 35,
                                    "color": "#fffb00"
                                },
                                {
                                    "id": 3,
                                    "value": 40,
                                    "color": "#f500f6"
                                }
                            ]
                    },
                    {
                        "id": 2,
                        "title": "Радиальная скорость",
                        "params":
                            [
                                {
                                    "id": 1,
                                    "value": 30,
                                    "color": "#010178"
                                },
                                {
                                    "id": 2,
                                    "value": 35,
                                    "color": "#fffb00"
                                },
                                {
                                    "id": 4,
                                    "value": 45,
                                    "color": "#f500f6"
                                }
                            ]
                    }
                ]        
        }
        
## Настройки цветовой шкалы [/settings/color_scale/{id}]

### Обновить настройки цветовой шкалы [PUT]

+ Request (application/json)

        [
            {
                "index": 1,
                "value": 30,
                "color": "#010178"
            },
            {
                "index": 2,
                "value": 35,
                "color": "#fffb00"
            },
            {
                "index": 3,
                "value": 40,
                "color": "#f500f6"
            }
        ]

+ Response 200 (application/json)

        {
            "count": 5,
            "rows": 
                [
                    {
                        "value": 30,
                        "color": "#010178"
                    },
                    {
                        "value": 35,
                        "color": "#fffb00"
                    },
                    {
                        "value": 40,
                        "color": "#f500f6"
                    }
                ]
        }
        
+ Response 422 (application/json)

        {
            "count": 1,
            "rows": 
                [
                    {
                        "id": 1,
                        "value": "Невалидное значение",
                        "color": "Невалидное значение"
                    }
                ]
        }
        
+ Response 404

## Настройки цветовой шкалы по умолчанию [/settings/color_scale/{id}/default]

### Получить настройки цветовой шкалы по умолчанию [GET]

+ Response 200 (application/json)
        
        {
            "count": 3,
            "rows":
                [
                    {
                        "id": 1,
                        "value": 30,
                        "color": "#010178"
                    },
                    {
                        "id": 2,
                        "value": 35,
                        "color": "#fffb00"
                    },
                    {
                        "id": 3,
                        "value": 40,
                        "color": "#f500f6"
                    }
                ]
        }